sudo: required
env:
  - IMAGENAME=cmgeorges/nodetest
services:
    - docker
script:
    #- docker image build -t ${IMAGENAME} .
    - docker images ${IMAGENAME}

before_deploy:
    - docker login -u ${USERNAME} -p ${PWD}

deploy:
  provider: script
  script: docker push ${IMAGENAME}
  on:
    branch: master