sudo: required
env:
  - IMAGENAME=cmgeorges/nodetest
services:
    - docker
before_install:
    - docker image build -t ${IMAGENAME} .
    #- docker images cmgeorges/node
script:
    #- docker image build -t ${IMAGENAME} .
    - docker images ${IMAGENAME}

