sudo: required
env:
  - IMAGENAME=cmgeorges/node-test
services:
    - docker
before_install:
  - docker build -t ${IMAGENAME} .
  - docker ps -a
script:
    #- docker image build -t ${IMAGENAME} .
    - docker images ${IMAGENAME}
    - docker tag ${IMAGENAME} ${IMAGENAME}:latest


deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master