sudo: required
env:
  - IMAGENAME=cmgeorges/node-test
services:
    - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# before_install:
#   - docker build -t ${IMAGENAME} .
#   - docker ps -a
script:
    - docker --version
    - docker build -t ${IMAGENAME} .
    #- docker images ${IMAGENAME}
    - docker tag ${IMAGENAME} ${IMAGENAME}:latest

after_success:
  - echo "$PWD" | docker login -u "$USERNAME" --password-stdin CMGeorges@github.com
  - docker push ${IMAGENAME}
# deploy:
#   provider: script
#   script: bash docker_push.sh
#   on:
#     branch: master