sudo: required
env:
  - IMAGENAME=cmgeorges/node-test
services:
    - docker
script:
    #- docker image build -t ${IMAGENAME} .
    - docker images ${IMAGENAME}

before_deploy:
    - docker login -u ${USERNAME} --password-stdin

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master